GET     http://localhost:3333/pessoas

###

PUT http://localhost:3333/atualizar?id=1
Content-Type: application/json

{
    "id": 1,
    "nome": "Diogo Martin Isaac Farias",
    "cpf": "65680742281",
    "dataNascimento": "1998-04-13",
    "telefone": "38988727840",
    "endereco": "Praça Vicente Mota, 976",
    "altura": 150,
    "peso": 80
}

###

